### PR TITLE
#59: Saving to file

### PR DESCRIPTION
**Pull request by adamjford**
There are some tests related to `ClaimSummaryFragment` that are erroring out but I can't figure out why. Someone else will need to figure out what's going on there, because I'm stumped.

#59

### CODE REVIEW

**Comment by adamjford** [comment]
In the process of merging `master` into this. Hold tight.

**Comment by adamjford** [comment]
Done!

**Comment by adamjford** [comment]
@ItsTristan Thanks for fixing that! Since you added some changes here, does that mean you've reviewed the rest, and that this is good to merge?

**Comment by adamjford** [comment]
Merging master in again.

**Comment by adamjford** [comment]
`master` merged in and good to go. Merge at your leisure if review is successful!

**Comment by ItsTristan** [comment]
Merge Approved.

**Pull request merged**
